### ISSUE TITLE
wkdev-enter fails because of missing /dev/input/eventX

### ISSUE THREAD

**Issue by cadubentzen** [Igalia/webkit-container-sdk#12]
`wkdev-enter --name wkdev` fails after a reboot. It doesn't show any logs with either `-v` or `--debug` (#2). However, manually running `podman start wkdev`, it yields this error message:

```
Error: unable to start container "a7ceb16fdf15a23733ea0f6537631e3cac1a9b73c48b6dd02073ed3ba802a9ea": crun: cannot stat `/dev/input/event11`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

May be related to https://github.com/containers/podman/issues/11239#issuecomment-940885242

**Comment by TingPing** [comment]
Could you test replacing this line:

https://github.com/Igalia/wkdev-sdk/blob/29ad39e9d5d89b8a894016ac5092d10694d036a0/scripts/host-only/wkdev-create#L402

With: `arguments+=("-v" "/dev/:/dev:rslave")` (It may need to be an earlier argument also.)

Then rerun `wkdev-create`, either with a new name or `--rm` to replace your existing one.
