### ISSUE TITLE
Add Instructions for Distrobox

### ISSUE THREAD

**Issue by danyeaw** [Igalia/webkit-container-sdk#22]
Hi, thanks for the SDK, this definitely makes setting up a development environment much easier!

As a distrobox user, I did something like:

```
distrobox create --image ghcr.io/wkdev:latest wkdev
distrobox enter wkdev
git clone https://github.com/WebKit/WebKit.git WebKit
cd WebKit
Tools/Scripts/build-webkit --gtk
```

Would you be open to adding distrobox instructions?

**Comment by TingPing** [comment]
While the image alone is very useful, we also have some custom scripts that are expected to be ran.

Maybe we could document that, someone will need to test and write it all down.

**Comment by nikolaszimmermann** [comment]
What came to your mind @TingPing?
@danyeaw - did you have any issues building + using WebKit this way?

**Comment by danyeaw** [comment]
Hi @nikolaszimmermann, with the steps above things worked great.

**Comment by TingPing** [comment]
What I meant is we have a list of custom permissions:

https://github.com/Igalia/webkit-container-sdk/blob/2bed97b7678ec3ab1dc7f44baa7dd580c5a8cd88/scripts/host-only/wkdev-create#L362

And we have an init script:

https://github.com/Igalia/webkit-container-sdk/blob/main/scripts/container-only/.wkdev-init

Distrobox itself handles some of the things we do but not necessarily all. So *running* WebKit may behave differently.

**Comment by danyeaw** [comment]
Hi @TingPing, thanks! I think we can go ahead and close this one then.
