### ISSUE TITLE
Sysprof support

### ISSUE THREAD

**Issue by GeorgesStavracas** [Igalia/webkit-container-sdk#25]
When running apps with `sysprof-cli`  and the Sysprof collector API (the WebKit use case, once the current WIP branch is finished), Sysprof sets the `SYSPROF_CONTROL_FD` file descriptor. This file descriptor is read by the Sysprof collector.

If this file descriptor can be mounted within the Podman container of the SDK, then we'll be able to use the profiler!

Sysprof also may set the `SYSPROF_TRACE_FD` fd, it might be worth passing it through too, but I'm not sure.

**Comment by TingPing** [comment]
I think this has some complexity inside of a sandbox. Christian writes about it here: https://blogs.gnome.org/chergert/2024/05/07/system-extensions-from-flatpak/

Only some of it applies to our situation, but like the policy-kit may. He also recommends disabling selinux. So there might be a bit to do here.

**Comment by nikolaszimmermann** [comment]
Fixed in main branch.
