### ISSUE TITLE
Tools/Scripts/run-web-platform-tests should recognize SDK environment

### ISSUE THREAD

**Issue by ptomato** [Igalia/webkit-container-sdk#47]
If you try to run WPT using `Tools/Scripts/run-web-platform-tests` inside an SDK container, it assumes that it needs to install a flatpak environment (which then fails). Instead, it should recognize that it's in the SDK environment.

Commenting out the flatpak check, the WPT script still doesn't run. I get the following error message, although I'm not sure if this is a problem on my end or with the dependencies in the SDK.

> An attempt has been made to start a new process before the current process has finished its bootstrapping phase. This probably means that you are not using fork to start your child processes ...

(plus some more probably irrelevant stuff about freezing executables)

**Comment by TingPing** [comment]
This is something to report to WebKit, it also must be a brand new regression.

The SDK sets the env var `WEBKIT_BUILD_USE_SYSTEM_LIBRARIES=1` and the scripts check that to never use flatpak.

**Comment by ptomato** [comment]
Reported: https://bugs.webkit.org/show_bug.cgi?id=280077
